#pragma once
#include "incomingPacket.h"

#define COMMAND_INCOMING_INIT 'i'
#define COMMAND_INCOMING_OLED 'o'
#define COMMAND_INCOMING_LEDS 'l'
#define COMMAND_INCOMING_FORCE_READ 'r'
#define COMMAND_INCOMING_CONFIG 'c'
#define COMMAND_INCOMING_HEARTBEAT 'h'
#define COMMAND_INCOMING_DISCONNECT 'd'

#define COMMAND_OUTGOING_BOOT '$'
#define COMMAND_OUTGOING_CHANNELS '='
#define COMMAND_OUTGOING_BUTTONS 'b'
#define COMMAND_OUTGOING_DEBUG '#'
#define COMMAND_OUTGOING_HEARTBEAT 'h'

#define COMMAND_OLED_ARGUMENT_SUBCOMMAND 0
#define COMMAND_OLED_ARGUMENT_VOLUME 1
#define COMMAND_OLED_ARGUMENT_VOLUME_CHANNEL 2
#define COMMAND_OLED_ARGUMENT_BRIGHTNESS 1
#define COMMAND_OLED_ARGUMENT_MUTE_UNMUTE 1
#define COMMAND_OLED_ARGUMENT_MUTE_CHANNEL 2
#define COMMAND_OLED_ARGUMENT_REGISTER_CHANNEL_NAMES_START 1
#define COMMAND_OLED_SUBCOMMAND_VOLUME '0'
#define COMMAND_OLED_SUBCOMMAND_CLEAR '1'
#define COMMAND_OLED_SUBCOMMAND_BRIGHTNESS '2'
#define COMMAND_OLED_SUBCOMMAND_MUTE '3'
#define COMMAND_OLED_SUBCOMMAND_REGISTER_CHANNEL_NAMES '4'

#define COMMAND_LEDS_ARGUMENT_SUBCOMMAND 0
#define COMMAND_LEDS_ARGUMENT_BRIGHTNESS 1
#define COMMAND_LEDS_SUBCOMMAND_SET '0'
#define COMMAND_LEDS_SUBCOMMAND_BRIGHTNESS '1'

#define COMMAND_CONFIG_ARGUMENT_BITFIELD_TYPE 0
#define COMMAND_CONFIG_ARGUMENT_BITFIELD_VALUE 0

#define COMMAND_HEARTBEAT_PING 's'
#define COMMAND_HEARTBEAT_PONG 'a'
#define COMMAND_HEARTBEAT_ARGUMENT_HEARTBEAT_TYPE 0

extern void (*commandMap[128])(IncomingPacket* pkt);

void initHandler();
void handleInit(IncomingPacket* pkt);
void handleOled(IncomingPacket* pkt);
void handleLeds(IncomingPacket* pkt);
void handleForceRead(IncomingPacket* pkt);
void handleConfig(IncomingPacket* pkt);
void handleHeartbeat(IncomingPacket* pkt);
void handleDisconnect(IncomingPacket* pkt);